version: "3"
services:
  jiramongodb:
    image: mongo:latest
    container_name: "jiramongodb"
    ports:
      - 27017:27017
#    volumes:
#      - data:/data
#  mongo-express:
#    image: mongo-express
#    container_name: mongo-express
#    restart: always
#    ports:
#      - 8081:8081
#    environment:
#      - ME_CONFIG_MONGODB_SERVER=mongodb
  springboot-mongodb:
    image: uvl-requirements-dashboard
    container_name: "springboot-mongodb"
    ports:
      - 9645:8080
    links:
      - jiramongodb
#volumes:
#  data: {}
#
#networks:
#  default:
#    name: mongodb_network