version: "3"
services:
  mongo:
    image: mongo:latest
    container_name: "mongo"
    ports:
      - 27017:27017
  springboot-mongodb:
    image: uvl-requirements-dashboard
    container_name: "springboot-mongodb"
    ports:
      - 9645:9645
    links:
      - mongo